---
- hosts: maas
  user: vagrant
  sudo: True
  tasks:
    - name: Install base packages and other usefulness
      action: apt pkg={{item}} state=installed update_cache=yes
      with_items:
        - language-pack-en-base
        - python-apt
        - python-pycurl
        - ubuntu-cloud-keyring
        - maas
        - maas-dns
        - maas-dhcp
    - name: Add maas superuser
      command: echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | sudo maas shell
    - name: Add boot images
      command: maas-import-pxe-files
