---
- hosts: all
  user: vagrant
  sudo: True
  tasks:
    - name: Install base packages and other usefulness
      action: apt pkg=$item state=installed update_cache=yes
      with_items:
        - language-pack-en-base
        - ubuntu-cloud-keyring
        - python-apt
        - python-pycurl
    - name: Add cloud repo
      apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/cloud-tools main' state=present update_cache=yes
    - name: Add cloud src repo
      apt_repository: repo='deb-src http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/cloud-tools main' state=present
    - name: install maas-enlist tool
      apt: pkg=maas-enlist state=installed
    - name: enlist node into maas
      shell: maas-enlist --serverurl 192.168.50.100 --interface eth1
